name: "🚀 Deploy React App via gh-pages"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build (with CI warnings suppressed)
      - name: Build without CI-errors
        env:
          CI: false
        run: npm run build

      # 5. Deploy via your gh-pages script
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
